algoritmo hospedagem
    inicio
    literal S, T, D
    caractere dia_semana
        escolha(dia_semana){
            caso S:
            escreva ("Simples , R$255,50");
            pare
            caso D:
            escreva("Duplo , R$305,50");
            pare
            caso T:
            escreva("Triplo, R$360,60");
            pare
            padrão:
            escreva("Esse dia é invalido")
        }  
    fim
